# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb7e82c4a3b314c89166e7a2a473bef3286d6299443ef55bf46dfa21b05f891407a5c50a1fe4e59a5660b756b1f1c8808900e3b84c17c34a4c937ac7614c55f5

test:
  secret_key_base: 07a9f7526aaa9090f98914d97d5feb51c91920f4974044e1240768c2c0242559117b04faa13800e26396d6baf5f987f9b444c69d82bbfaf4bff251e186907bbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
